### PR TITLE
omero-py 5.8.1

### PR DESCRIPTION
**Pull request by jburel**
Bump to 5.8.1 version

### CODE REVIEW

**Comment by manics** [comment]
Looks OK.... waiting for travis to check ....

**Comment by joshmoore** [comment]
re-opening, but perhaps by the time travis is green we'll have a 5.8.2...

**Review by sbesson — APPROVED** [review]
Looks good. Merging (so that we have a record and I'll open a follow-up to bump to 5.8.2

NB: while briefly looking at converting Travis CI -> GitHub actions https://github.com/marketplace/actions/publish-conda and https://github.com/marketplace/actions/anaconda-action might be community actions worth looking into

**Comment by joshmoore** [comment]
Those look nice. Would obviously require a little reworking of the source to get rid of the `conda-*` packages, but it'd be much more bulletproof.

**Pull request merged**
