### PR TITLE
Test upgrading the conda set-up role

### PR DESCRIPTION
**Pull request by sbesson**
Attempts to fix https://github.com/ome/conda-omero-py/pull/18#issuecomment-988790853 by upgrading the base action

### CODE REVIEW

**Comment by jburel** [comment]
installing ``conda install -c anaconda urllib3`` fixes the issue for all Python version. The problem is related to Windows.  See https://github.com/jburel/conda-omero-py/actions/runs/1554376749

**Comment by jburel** [comment]
@sbesson I tested that option too and it works https://github.com/jburel/conda-omero-py/runs/4458538731?check_suite_focus=true

**Comment by sbesson** [comment]
Primarily inspired by https://github.com/conda/conda/issues/9903#issuecomment-647091019 and using the upstream action flag

**Review by jburel — APPROVED** [review]

**Comment by jburel** [comment]
The change will need to be applied to the other conda repositories

**Pull request merged**
