### PR TITLE
omero-py 5.6.dev9 

### PR DESCRIPTION
**Pull request by manics**
Bump version
Tag: `5.6.dev9-0`

### CODE REVIEW

**Comment by jburel** [comment]
The dependencies match the list of omero-py
Maybe I am missing something in the way it works, but I will have assumed the dependencies will have been fetched when omero-py is installed.

**Comment by manics** [comment]
They're completely independent, there's no way for conda to know the correspondence between the name of a package on pypi and the name of an equivalent conda package.

**Comment by jburel** [comment]
I will read a bit more. Nothing to do with this PR

**Comment by joshmoore** [comment]
We probably could use some reminders in the omero-py README and/or RELEASE docs and/or automation to keep everything in sync.

**Pull request merged**
